apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: citus-manager 
spec:
  selector:
    matchLabels:
      app: citus-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: citus-manager
    spec:
      serviceAccountName: {{ .Values.manager.serviceAccountName }}
      containers:
      - name: citus-manager-container
        image: bakdata/citus-k8s-membership-manager:v0.2
        imagePullPolicy: Always
        volumeMounts:
        - name: citus-config-mount
          mountPath: {{ .Values.manager.provision.mountPath }}
        resources:
 {{ toYaml .Values.manager.resources | indent 12 }}
        env:
        - name: NAMESPACE
          value: {{ .Values.manager.namespace }}
        - name: SHORT_URL
          value: "{{ .Values.manager.shortUrl }}"
        - name: WORKER_SERVICE
          value: {{ template "citus-postgresql.fullname" . }}-worker
        - name: MASTER_SERVICE 
          value: {{ template "citus-postgresql.fullname" . }}-master
        - name: PG_PASSWORD
          value: "{{ .Values.superuser.password }}"
        - name: PG_USER
          value: {{ .Values.superuser.username }}
        - name: MASTER_PROVISION_FILE
          value: {{ .Values.manager.provision.mountPath }}{{ .Values.manager.provision.masterFile }}
        - name: WORKER_PROVISION_FILE
          value: {{ .Values.manager.provision.mountPath }}{{ .Values.manager.provision.workerFile }}

        - name: MINIMUM_WORKERS
          value: "{{ .Values.manager.minimumWorkers }}"
      volumes:
      - name: citus-config-mount
        configMap:
          name: setup-config
